name = "shouye-platform"
main = "src/worker.ts"
compatibility_date = "2026-05-02"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "shouye-platform-db"
database_id = "db86ef5e-4044-4107-88a9-9dc497bbfe3f"
migrations_dir = "migrations"

[vars]
ADMIN_USERNAME = "l243736590"
ADMIN_PASSWORD_HASH = "8e20b592394cac7f7faf7b1df2d2e6295d8df4b926f14d96496c7573cb8bcf04"
