const schools = [
  { id: 'yonsei', name: '延世大学', city: '首尔', tags: ['经营', '传媒', '语学院'], image: '/schools/yonsei/1.jpg' },
  { id: 'cau', name: '中央大学', city: '首尔', tags: ['艺术', '传媒', '戏剧'], image: '/schools/cau/1.jpg' },
  { id: 'hongik', name: '弘益大学', city: '首尔', tags: ['艺术', '设计', '建筑'], image: '/schools/hongik/1.jpg' },
  { id: 'sogang', name: '西江大学', city: '首尔', tags: ['经营', '传媒', '国际学'], image: '/schools/sogang/1.jpg' },
  { id: 'konkuk', name: '建国大学', city: '首尔', tags: ['语学院', '本科', '生活'], image: '/schools/konkuk/1.jpg' },
  { id: 'kookmin', name: '国民大学', city: '首尔', tags: ['设计', '汽车', '工科'], image: '/schools/kookmin/1.jpg' },
  { id: 'uos', name: '首尔市立大学', city: '首尔', tags: ['公立', '城市', '费用友好'], image: '/schools/uos/1.jpg' },
  { id: 'knua', name: '韩国艺术综合学校', city: '首尔', tags: ['艺术', '音乐', '表演'], image: '/schools/knua/1.jpg' }
]

const questionCategories = [
  '签证/滞留资格',
  '入学须知',
  '找房与转租',
  '找兼职与代兼职',
  '医院与保险',
  '作业与论文',
  '周边生活攻略',
  '同好与交友',
  '跳蚤市场',
  '八卦与吃瓜',
  '抱团选课',
  '各种吐槽'
]

const postCategories = [
  '签证/滞留资格',
  '入学须知',
  '找房与转租',
  '找兼职与代兼职',
  '医院与保险',
  '作业与论文',
  '周边生活攻略',
  '同好与交友'
]

const skillCategories = [
  '宠物照看/遛狗喂猫',
  '跑腿/排队/代办',
  '地陪/陪同/翻译',
  '学习辅导/资料整理',
  '搬家/取送/寄件',
  '同校生活帮忙',
  '其他技能服务'
]

const partnerCategories = [
  {
    id: 'consulting',
    title: '留学咨询',
    subtitle: '择校、材料、签证、语学院和大学院申请'
  },
  {
    id: 'academic',
    title: '学业相关',
    subtitle: '韩语写作、发表准备、课业答疑和选课支持'
  },
  {
    id: 'food',
    title: '餐饮相关',
    subtitle: '中餐、外卖、夜宵、聚餐和校园团购'
  },
  {
    id: 'logistics',
    title: '物流快递',
    subtitle: '行李托运、海运、转运、同城配送和文件快递'
  },
  {
    id: 'telecom',
    title: '通信',
    subtitle: '电话卡、流量卡、宽带、Wi-Fi 和号码实名'
  },
  {
    id: 'home',
    title: '家政搬家',
    subtitle: '搬家、退租清洁、家具处理、维修和上门安装'
  },
  {
    id: 'housing',
    title: '不动产',
    subtitle: '找房、转租、保证金风险和合同确认'
  }
]

const fallbackQuestions = [
  {
    id: 'q-d2-extension',
    title: '韩国D-2签证延长需要哪些材料？',
    category: '签证/滞留资格',
    school: '中央大学',
    rewardPoints: 120,
    answersCount: 8,
    views: 2860,
    status: 'solved',
    createdAt: '2026-05-03',
    tags: ['D-2', '延签', '在学证明'],
    detail: '第一次延长 D-2，想确认在学证明、成绩单、住宿证明和银行材料怎么准备。签证和滞留资格要求以 HiKorea、出入境和学校最新公告为准。'
  },
  {
    id: 'q-d10-jobseeker',
    title: '毕业后D-10求职签证怎么申请？',
    category: '签证/滞留资格',
    school: '西江大学',
    rewardPoints: 150,
    answersCount: 9,
    views: 2190,
    status: 'open',
    createdAt: '2026-04-24',
    tags: ['D-10', '毕业', '求职'],
    detail: '硕士快毕业，想从 D-2 转 D-10。希望了解毕业材料、求职计划书和预约经验，最终以官方窗口要求为准。'
  },
  {
    id: 'q-arc-lost',
    title: '外国人登录证丢了怎么办？',
    category: '签证/滞留资格',
    school: '釜山大学',
    rewardPoints: 80,
    answersCount: 6,
    views: 1520,
    status: 'open',
    createdAt: '2026-05-01',
    tags: ['外国人登录证', '补办', '地址'],
    detail: '钱包丢了，里面有外国人登录证。想知道要不要先报警、去哪里补办、补办期间银行和学校业务怎么处理。'
  },
  {
    id: 'q-rent-deposit',
    title: '韩国租房保证金怎么防止被骗？',
    category: '找房与转租',
    school: '延世大学',
    rewardPoints: 160,
    answersCount: 14,
    views: 4210,
    status: 'solved',
    createdAt: '2026-05-02',
    tags: ['租房', '保证金', '合同'],
    detail: '准备住新村附近，房东要求先转一部分保证金。想知道签合同前应该查哪些信息，哪些情况不能转账。'
  },
  {
    id: 'q-one-room-contract',
    title: '韩国 one-room 合同签之前要看哪些条款？',
    category: '找房与转租',
    school: '建国大学',
    rewardPoints: 110,
    answersCount: 6,
    views: 2210,
    status: 'open',
    createdAt: '2026-04-23',
    tags: ['one-room', '合同', '建大入口'],
    detail: '准备在 건대입구역 附近签 one-room，想确认管理费、退租、维修、地址申报和保证金返还这些条款。'
  },
  {
    id: 'q-bank-account',
    title: '韩国银行卡开户需要什么？',
    category: '周边生活攻略',
    school: '建国大学',
    rewardPoints: 60,
    answersCount: 7,
    views: 1986,
    status: 'solved',
    createdAt: '2026-04-30',
    tags: ['银行卡', '本人认证', '外国人登录证'],
    detail: '刚拿到外国人登录证，想去学校附近银行开户。需要学生证、手机号、在学证明或住所信息吗？'
  },
  {
    id: 'q-phone-plan',
    title: '韩国手机卡怎么选？',
    category: '周边生活攻略',
    school: '弘益大学',
    rewardPoints: 50,
    answersCount: 4,
    views: 1320,
    status: 'open',
    createdAt: '2026-04-26',
    tags: ['手机卡', '本人认证', '预付卡'],
    detail: '想知道预付卡、알뜰폰、合约套餐怎么选，主要需要韩国手机号认证和日常流量。'
  },
  {
    id: 'q-hospital-insurance',
    title: '韩国看病怎么用保险？',
    category: '医院与保险',
    school: '忠南大学',
    rewardPoints: 70,
    answersCount: 6,
    views: 1588,
    status: 'solved',
    createdAt: '2026-04-25',
    tags: ['医院', '保险', '药店'],
    detail: '想知道国民健康保险怎么用，去医院挂号、缴费、拿药分别怎么做，医疗判断以医生意见为准。'
  },
  {
    id: 'q-work-hours',
    title: '韩国留学生可以合法打工多少小时？',
    category: '找兼职与代兼职',
    school: '高丽大学',
    rewardPoints: 100,
    answersCount: 10,
    views: 3420,
    status: 'open',
    createdAt: '2026-04-29',
    tags: ['打工许可', '兼职', '以公告为准'],
    detail: '想确认 D-2/D-4 留学生打工许可、每周小时数和假期限制。打工和滞留资格内容以官方最新公告为准。'
  },
  {
    id: 'q-wage-arrears',
    title: '韩国兼职工资被拖欠，留学生应该怎么留证据？',
    category: '找兼职与代兼职',
    school: '高丽大学',
    rewardPoints: 140,
    answersCount: 9,
    views: 3140,
    status: 'open',
    createdAt: '2026-04-22',
    tags: ['工资拖欠', '兼职', '劳动纠纷'],
    detail: '店里一直说下周给工资，但没有按时结算。想知道排班、聊天记录、转账和劳动合同怎么整理。'
  },
  {
    id: 'q-language-to-undergrad',
    title: '语学院转本科需要什么流程？',
    category: '入学须知',
    school: '庆熙大学',
    rewardPoints: 90,
    answersCount: 5,
    views: 1760,
    status: 'open',
    createdAt: '2026-04-28',
    tags: ['语学院', '本科申请', '材料'],
    detail: '目前语学院 4 级，想申请同校本科。想知道语言成绩、出勤、推荐信和材料时间线怎么安排。'
  },
  {
    id: 'q-grad-course-registration',
    title: '韩国大学院第一学期选课怎么避免选错？',
    category: '抱团选课',
    school: '汉阳大学',
    rewardPoints: 90,
    answersCount: 5,
    views: 1680,
    status: 'solved',
    createdAt: '2026-04-21',
    tags: ['大学院', '选课', '学分'],
    detail: '刚进大学院，不确定专业必修、研究学分、导师推荐课和毕业学分怎么一起看。'
  },
  {
    id: 'q-thesis-delay',
    title: '韩国大学院论文延期怎么办？',
    category: '作业与论文',
    school: '汉阳大学',
    rewardPoints: 180,
    answersCount: 11,
    views: 2670,
    status: 'solved',
    createdAt: '2026-04-27',
    tags: ['论文', '延毕', '大学院'],
    detail: '论文进度慢，导师建议延期。想知道延期申请、学费、签证和毕业时间线会有什么影响。'
  },
  {
    id: 'q-graduation-documents',
    title: '韩国大学毕业材料一般要提前准备什么？',
    category: '作业与论文',
    school: '西江大学',
    rewardPoints: 75,
    answersCount: 4,
    views: 1280,
    status: 'open',
    createdAt: '2026-04-20',
    tags: ['毕业材料', '成绩单', '认证'],
    detail: '想提前准备毕业证明、成绩单、学位证明和回国认证材料。哪些文件要等毕业后才能拿？'
  },
  {
    id: 'q-moving-process',
    title: '首尔搬家流程和地址变更怎么安排？',
    category: '周边生活攻略',
    school: '延世大学',
    rewardPoints: 65,
    answersCount: 5,
    views: 1460,
    status: 'solved',
    createdAt: '2026-04-19',
    tags: ['搬家', '地址变更', '退租'],
    detail: '从新村搬到弘大附近，想知道搬家公司、家具处理、水电气网结算、押金返还和地址变更顺序。'
  },
  {
    id: 'q-trash-sorting',
    title: '韩国垃圾分类和大型废弃物到底怎么扔？',
    category: '周边生活攻略',
    school: '中央大学',
    rewardPoints: 40,
    answersCount: 6,
    views: 1850,
    status: 'open',
    createdAt: '2026-04-18',
    tags: ['垃圾分类', '大型废弃物', '生活'],
    detail: '搬进 one-room 后不知道厨余、一般垃圾、回收和旧家具分别怎么扔。不同区规则是不是不一样？'
  },
  {
    id: 'q-secondhand-trade',
    title: '韩国二手交易买电器怎么避坑？',
    category: '跳蚤市场',
    school: '韩国生活',
    rewardPoints: 55,
    answersCount: 7,
    views: 1730,
    status: 'solved',
    createdAt: '2026-04-17',
    tags: ['二手交易', '电器', '面交'],
    detail: '想买二手冰箱和微波炉，担心坏机、搬运费和先转账被骗，希望有经验的人给面交检查清单。'
  },
  {
    id: 'q-school-dorm',
    title: '韩国学校宿舍申请失败后怎么找过渡住处？',
    category: '找房与转租',
    school: '延世大学',
    rewardPoints: 85,
    answersCount: 6,
    views: 1920,
    status: 'open',
    createdAt: '2026-04-16',
    tags: ['学校宿舍', '考试院', '短租'],
    detail: '宿舍没申请上，离入学只剩一段时间。想知道考试院、短租、guesthouse 和 one-room 哪种适合作为过渡。'
  },
  {
    id: 'q-legal-exchange-channel',
    title: '留学生怎么走合法渠道换钱和取钱？',
    category: '周边生活攻略',
    school: '韩国留学',
    rewardPoints: 190,
    answersCount: 5,
    views: 4520,
    status: 'solved',
    createdAt: '2026-05-05',
    tags: ['银行卡', '海外汇款', 'ATM'],
    detail: '建议优先使用本人银行卡、ATM 提款、银行购汇和海外汇款渠道。平台严禁发布私人换钱、换米广告和撮合求助。'
  },
  {
    id: 'q-private-exchange-frozen',
    title: '私人换钱收到黑钱，银行卡被冻结怎么办？',
    category: '周边生活攻略',
    school: '韩国留学',
    rewardPoints: 185,
    answersCount: 7,
    views: 4380,
    status: 'solved',
    createdAt: '2026-05-05',
    tags: ['换汇风险', '冻结账户', '法律风险'],
    detail: '保留聊天记录、转账记录和对方信息，尽快联系开户行说明情况，并根据银行和警方要求配合处理。'
  }
]

const fallbackPosts = [
  {
    id: 'korea-rent-deposit-guide',
    slug: 'korea-rent-deposit-guide',
    title: '韩国租房保证金避坑：签合同前先查这几件事',
    summary: '把 one-room、考试院、转租和保证金风险拆开看，先核对房东、中介、合同、登记和转账对象。',
    school: '韩国生活',
    category: '找房与转租',
    author: '首尔租房过来人',
    price: 0,
    hot: '精华',
    views: 8420,
    likes: 512,
    bookmarks: 1120,
    tags: ['韩国', '租房', '保证金', 'one-room', '转租', '合同'],
    excerpt: '租房不要只看照片和离学校近，真正要核对的是房东身份、登记簿、押金流向和退租条款。',
    body: `适用人群：准备在韩国租 one-room、考试院、宿舍外住房，或者接手转租的留学生。
准备重点：看房前先确认房源地址、房东身份、中介资质、保证金金额、月租、管理费包含项目和可否做住所申报。签约前要求查看登记簿，确认出租人和收款账户是否一致。转租一定要确认原合同是否允许转租，房东是否书面同意。
步骤：先按学校和通学圈筛房源，再现场看房，检查采光、热水、水压、霉味、门锁、垃圾点、夜路和坡度；确认合同主体、押金返还日期、提前退租规则、维修责任；转账时保留收款人、金额和备注；入住当天拍照留底，并及时处理地址变更。
常见坑：远程只看视频就付定金；把押金转给非房东账户；口头承诺不写进合同；管理费包含项目含糊；退租时才发现清洁费、维修费和违约金争议。
检查清单：房东身份、登记簿、中介信息、合同原件、收款账户、押金返还日、管理费明细、住所申报材料、入住照片、退租通知方式。
免责声明：本文是经验整理，不构成法律意见。租房登记、押金保障和合同处理以韩国当地窗口、学校国际处和正式合同为准。平台严禁发布换钱换米、非法换汇相关求助和广告。`,
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
    featured: true,
    isFeatured: true
  },
  {
    id: 'd2-visa-extension-guide',
    slug: 'd2-visa-extension-guide',
    title: 'D-2 签证延长：别等到期前一周才开始',
    summary: '按时间线整理 D-2 延签的预约、学校材料、住址证明、资金证明和补件风险。',
    school: '中央大学',
    category: '签证/滞留资格',
    author: '中央大学大学院在读',
    price: 0,
    hot: '精华',
    views: 7680,
    likes: 463,
    bookmarks: 980,
    tags: ['D-2', '延签', 'HiKorea', '在学证明', '以公告为准'],
    excerpt: 'D-2 延签的难点不是填表，而是预约、学校证明、住所证明和补件时间。',
    body: `适用人群：D-2 在读本科、大学院学生，特别是第一次延签、论文阶段、超学期或刚搬家的同学。
准备材料：护照、外国人登录证、申请书、手续费相关材料、在学证明、成绩单、学费缴纳或注册确认、住所证明，以及窗口要求的补充材料。资金证明是否需要、金额和开具方式会因个人状态和窗口要求不同而变化，不要照搬同学去年的材料。
步骤：先确认外国人登录证背面滞留期限；提前看 HiKorea 是否有可预约时间；向学校开近期证明；核对住所证明和地址；整理文件原件与复印件；按预约或电子申请要求提交；保存回执和补件通知。
常见坑：搬家后没处理地址导致住所材料对不上；成绩、出勤或论文阶段需要补充说明却没准备；银行证明日期过旧；临近到期才发现预约满；只听群里经验，没看学校国际处最新说明。
检查清单：滞留期限、预约日期、学校材料、住所证明、姓名拼写、联系方式、补件渠道、回执截图。
免责声明：签证、打工、滞留资格内容会调整，最终以 HiKorea、出入境事务所、1345 咨询和学校国际处最新公告为准。`,
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
    featured: true,
    isFeatured: true
  },
  {
    id: 'alien-registration-card-guide',
    slug: 'alien-registration-card-guide',
    title: '外国人登录证办理与地址信息检查',
    summary: '从入境后预约、住址证明、领取后核对，到后续银行、手机卡和地址变更的注意事项。',
    school: '建国大学',
    category: '签证/滞留资格',
    author: '建大本科生',
    price: 0,
    hot: '精华',
    views: 6510,
    likes: 396,
    bookmarks: 865,
    tags: ['外国人登录证', 'ARC', '地址变更', 'HiKorea', '生活'],
    excerpt: '外国人登录证会影响银行、手机卡、医保、网购认证和后续签证，别把它当成普通证件。',
    body: `适用人群：持长期留学签证入境韩国，准备办理外国人登录证，或已经换住处需要检查地址信息的同学。
准备材料：护照、申请书、证件照、学校入学或在学相关材料、住所证明、手续费相关材料，以及出入境或学校要求的补充文件。宿舍、本人租房、借住、转租所需材料可能不同，地址要和实际居住地一致。
步骤：参加学校团体办理说明会，或自行查看 HiKorea 预约入口；按学校国际处清单准备申请表、照片和学校材料；确认住所证明；提交材料并保存回执；领取后核对姓名、生日、国籍、滞留资格、期限和地址；拿证后再补齐银行、手机号码和医保资料。
常见坑：临时住所写成长期地址，之后搬家忘记变更；照片规格、姓名拼写或宿舍证明不符合窗口要求；把登录证正反面随便发给陌生中介或群友，增加身份信息风险。
检查清单：预约方式、学校材料、住所证明、证件照、护照信息、申请回执、领取后信息核对、后续地址变更。
免责声明：外国人登录证和地址变更要求以 HiKorea、出入境、1345 和学校最新公告为准。`,
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
    featured: true,
    isFeatured: true
  },
  {
    id: 'korea-bank-account-guide',
    slug: 'korea-bank-account-guide',
    title: '韩国银行卡开户与本人认证攻略',
    summary: '开户前准备外国人登录证、手机号码、学校信息和账户用途说明，避免后续认证失败。',
    school: '韩国生活',
    category: '周边生活攻略',
    author: '首尔生活记录员',
    price: 0,
    hot: '精华',
    views: 5920,
    likes: 310,
    bookmarks: 730,
    tags: ['银行卡', '开户', '手机认证', '生活', '金融风险'],
    excerpt: '韩国开户不只是拿护照办卡，重点看 ARC、手机号、住址、账户用途和姓名录入。',
    body: `适用人群：刚拿到外国人登录证，准备办韩国银行卡和手机银行的留学生。
准备材料：外国人登录证、护照、韩国本人名义手机号、学生证或在学证明、住址信息、账户用途说明。建议优先去学校合作银行或学校附近常办外国人业务的支行。
步骤：确认 ARC、手机号和护照姓名拼写一致；说明账户用途，例如生活费、房租、学费和日常消费；开卡时问清每日转账限额、手机银行、OTP 或安全卡、交通卡功能、海外转账和刷卡功能；回家后立刻测试手机银行登录和小额转账。
常见坑：银行、手机号、ARC 姓名差一个空格导致 KakaoPay、Toss、网购或医院预约认证失败；没问转账限额，交房租时才发现转不出去；用朋友手机号开户，后续找回账号困难。
检查清单：ARC 已领取、手机号本人名义、姓名一致、手机银行可登录、转账限额确认、卡片功能确认、银行回执保存。
免责声明：本文不构成金融建议。银行开户、反洗钱审查和账户限制以各银行窗口、官方客服和学校合作银行最新要求为准。平台严禁发布私下换汇和换钱换米广告。`,
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
    featured: true,
    isFeatured: true
  },
  {
    id: 'korea-part-time-work-guide',
    slug: 'korea-part-time-work-guide',
    title: '韩国留学生打工许可与工资留证指南',
    summary: '打工前先确认签证资格、学校同意、雇主信息和时间制就业许可，工资纠纷时保留证据。',
    school: '高丽大学',
    category: '找兼职与代兼职',
    author: '安岩兼职过来人',
    price: 0,
    hot: '精华',
    views: 6140,
    likes: 355,
    bookmarks: 810,
    tags: ['打工', '兼职许可', '工资拖欠', 'HiKorea', '以公告为准'],
    excerpt: '留学生打工不要先上班再补手续，先确认许可范围、雇主地点、合同和工资记录。',
    body: `适用人群：D-2、D-4 在读期间准备兼职，或已经遇到排班、工资、合同纠纷的同学。
准备材料：护照、外国人登录证、申请书、在学或出勤/成绩相关材料、时间制就业确认书、劳动合同、雇主营业执照或相关证明、学校国际处确认材料。不同签证、学历阶段、语言能力、出勤和学校认证状态会影响要求。
步骤：先确认自己是否有资格申请时间制就业；和雇主确认工资、地点、岗位、每周时间和结算日；签书面劳动合同；让学校国际处确认材料；通过 HiKorea 或出入境要求的方式申请许可；许可结果明确后再按许可范围工作；每次上班保存排班、打卡、聊天和工资记录。
常见坑：未许可先上班；许可地点和实际地点不一致；超出允许范围工作；换店不重新确认；工资现金结算没有记录。工资拖欠时，不要只靠口头承诺，要整理合同、排班表、聊天记录、转账记录、店铺信息和同事证言。
检查清单：资格确认、学校同意、雇主信息、合同、许可范围、排班记录、工资记录、纠纷证据。
免责声明：签证、打工和滞留资格要求会调整，最终以 HiKorea、出入境、1345、雇佣劳动部和学校国际处最新公告为准。`,
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
    featured: true,
    isFeatured: true
  },
  {
    id: 'd10-job-seeking-visa-guide',
    slug: 'd10-job-seeking-visa-guide',
    title: '毕业后 D-10 求职签证准备清单',
    summary: '从毕业状态、求职计划、学校材料和预约节点整理 D-10 准备思路。',
    school: '西江大学',
    category: '签证/滞留资格',
    author: '毕业求职中',
    price: 0,
    hot: '干货',
    views: 3820,
    likes: 188,
    bookmarks: 430,
    tags: ['D-10', '求职', '毕业', 'Korea Visa Portal'],
    excerpt: 'D-10 的重点是毕业状态、求职计划、材料一致性和时间衔接。',
    body: `适合毕业后想继续在韩国求职、实习或准备就业转换的同学。先确认 D-2 到期日、毕业或预毕业状态、学校能开哪些材料，再准备求职计划书、简历、学历或成绩材料、住所证明和官方要求的补充材料。常见坑是时间衔接太紧、计划书写得空泛、地址证明过期、毕业状态和材料日期对不上。提示：D-10 和滞留资格要求以 HiKorea、Korea Visa Portal、出入境、1345 和学校公告为准。`,
    createdAt: '2026-05-05',
    updatedAt: '2026-05-05',
    featured: true,
    isFeatured: true
  },
  {
    id: 'korea-moving-trash-guide',
    slug: 'korea-moving-trash-guide',
    title: '韩国搬家、退租和垃圾处理流程',
    summary: '把搬家公司、地址变更、水电气网结算、旧家具处理和垃圾分类按顺序排好。',
    school: '韩国生活',
    category: '周边生活攻略',
    author: '搬家三次的学姐',
    price: 0,
    hot: '干货',
    views: 3560,
    likes: 176,
    bookmarks: 390,
    tags: ['搬家', '垃圾分类', '退租', '地址变更'],
    excerpt: '搬家不是只叫车，退租、押金、地址变更和大件垃圾处理都要提前安排。',
    body: `搬家前先确认退租通知期限、押金返还日、清洁要求和水电气网结算。搬家公司报价要说清楼层、电梯、大件家具、距离和是否需要拆装。旧家具和大件垃圾不要随便丢，不同地区需要购买或申请大型废弃物贴纸。搬家后及时处理外国人登录证地址变更，并把新地址同步给银行、手机、学校和医保相关渠道。`,
    createdAt: '2026-05-05',
    updatedAt: '2026-05-05',
    featured: true,
    isFeatured: true
  },
  {
    id: 'korea-new-student-checklist',
    slug: 'korea-new-student-checklist',
    title: '韩国留学生新生 checklist：落地前后按这个排',
    summary: '把机票、住宿、入学、登录证、银行卡、手机卡、医保和学校系统排成时间线。',
    school: '韩国留学',
    category: '入学须知',
    author: '新生接机志愿者',
    price: 0,
    hot: '清单',
    views: 4980,
    likes: 260,
    bookmarks: 620,
    tags: ['新生', 'checklist', '入学', '生活'],
    excerpt: '新生不要所有事一起做，先按落地前、落地第一周、开学后一个月拆任务。',
    body: `落地前确认签证、机票、临时住宿、学校报到时间和必带文件。落地第一周先解决住宿、电话卡、学校报到、校园系统和生活必需品。开学后一个月重点处理外国人登录证、银行卡、医保、选课和地址信息。所有文件建议做电子扫描备份，重要通知关注学校国际处和邮箱。`,
    createdAt: '2026-05-05',
    updatedAt: '2026-05-05',
    featured: true,
    isFeatured: true
  },
  {
    id: 'post-cau-heukseok-rent',
    slug: 'post-cau-heukseok-rent',
    title: '中央大学黑石洞找房与转租避坑',
    summary: '按黑石洞、上道、鹭梁津和 9 号线通勤，把中央大学周边找房风险拆清楚。',
    school: '中央大学',
    category: '找房与转租',
    author: '黑石洞租房过来人',
    price: 0,
    hot: '学校',
    views: 3740,
    likes: 206,
    bookmarks: 488,
    tags: ['中央大学', '黑石洞', '上道', '租房', '转租'],
    excerpt: '中央大周边别只盯正门距离，坡度、夜路、通勤和押金安全要一起看。',
    body: `中央大学首尔校区找房，黑石洞步行圈方便但坡多，房源差异大；上道、鹭梁津和 9 号线沿线可选范围更广。转租要核对原合同是否允许、房东是否书面同意、押金退给谁。看房时重点查热水、水压、采光、霉味、门锁、垃圾点和夜路。`,
    createdAt: '2026-05-04',
    updatedAt: '2026-05-04',
    featured: true
  },
  {
    id: 'post-art-admission-portfolio',
    slug: 'post-art-admission-portfolio',
    title: '韩国艺术类入学：作品集和学校选择怎么看',
    summary: '艺术、设计、传媒、戏剧影视方向不要只看排名，要同时看作品集、面试和课程方向。',
    school: '韩国大学',
    category: '入学须知',
    author: '艺术专业申请过来人',
    price: 0,
    hot: '艺术',
    views: 3310,
    likes: 198,
    bookmarks: 450,
    tags: ['艺术类', '作品集', '弘益大学', '中央大学', '入学'],
    excerpt: '艺术类入学第一步不是问排名，而是确认专业方向、作品集格式和面试要求。',
    body: `先分清美术、视觉设计、产业设计、影像、电影、戏剧、音乐、舞蹈、传媒和文化内容方向。每个院系对页数、格式、链接权限、原创声明、面试或实技要求不同。建议把目标学校简章、作品集要求、语言成绩、学历材料和面试节点做成表格，避免截止前才发现格式不符。`,
    createdAt: '2026-05-04',
    updatedAt: '2026-05-04',
    featured: true
  },
  {
    id: 'post-phone-card',
    slug: 'post-phone-card',
    title: '韩国手机卡办理：预付卡、MVNO 和合约怎么选',
    summary: '先解决落地联网，再考虑本人认证、流量、违约金和长期套餐。',
    school: '韩国生活',
    category: '周边生活攻略',
    author: '首尔生活记录员',
    price: 0,
    hot: '生活',
    views: 2710,
    likes: 124,
    bookmarks: 280,
    tags: ['手机卡', '本人认证', '流量', '预付卡'],
    excerpt: '刚落地不一定要立刻签长期合约，先看能不能认证、能不能收验证码。',
    body: `刚到韩国可以先用预付卡或 eSIM 解决导航、联系房东和收验证码。拿到外国人登录证后，建议办理本人名义手机号，银行、网购、外卖、医院预约和快递都会用到认证。预付卡快但认证能力有限，MVNO 便宜但要确认支持外国人，三大运营商稳定但违约成本可能更高。`,
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
    featured: false
  },
  {
    id: 'post-hospital-insurance',
    slug: 'post-hospital-insurance',
    title: '韩国看病和保险：第一次去医院怎么走流程',
    summary: '从选医院、挂号、缴费、拿药到保险通知，把第一次看病的流程拆开。',
    school: '韩国生活',
    category: '医院与保险',
    author: '第一次看病记录',
    price: 0,
    hot: '生活',
    views: 2990,
    likes: 143,
    bookmarks: 310,
    tags: ['医院', '保险', '药店', 'NHIS'],
    excerpt: '韩国看病通常是医院诊疗后拿处方，再去药店取药，保险状态要提前确认。',
    body: `第一次看病先确认是普通诊所、专科医院还是大学医院，带外国人登录证和保险相关信息。挂号时说明症状，缴费后看医生，拿处方去药店取药。国民健康保险、学校保险和商业保险覆盖范围不同，报销或减免以保险机构和医院说明为准。医疗判断以医生意见为准。`,
    createdAt: '2026-04-28',
    updatedAt: '2026-04-28',
    featured: false
  },
  {
    id: 'post-grad-course-registration',
    slug: 'post-grad-course-registration',
    title: '韩国大学院第一学期选课：先看毕业条件再抢课',
    summary: '大学院选课要同时看必修、研究学分、导师建议和毕业要求。',
    school: '汉阳大学',
    category: '抱团选课',
    author: '研一过来人',
    price: 0,
    hot: '选课',
    views: 2360,
    likes: 112,
    bookmarks: 255,
    tags: ['大学院', '选课', '学分', '导师'],
    excerpt: '研究生第一学期别只看课名，要先确认毕业学分、必修和导师建议。',
    body: `大学院选课先看专业毕业条件：总学分、专业必修、研究学分、论文资格考试和语言要求。再问导师或实验室前辈哪些课适合第一学期上。韩文授课、英文授课、发表要求和小组作业强度都要提前确认。不要为了凑时间表选和研究方向完全无关的课。`,
    createdAt: '2026-04-27',
    updatedAt: '2026-04-27',
    featured: false
  },
  {
    id: 'post-thesis-process',
    slug: 'post-thesis-process',
    title: '韩国大学院论文流程：开题、审查和延期怎么安排',
    summary: '把导师沟通、研究计划、伦理审查、论文审查和延毕风险按时间线整理。',
    school: '西江大学',
    category: '作业与论文',
    author: '论文卡住的人',
    price: 0,
    hot: '论文',
    views: 3190,
    likes: 168,
    bookmarks: 410,
    tags: ['论文', '延毕', '大学院', '导师'],
    excerpt: '论文不是最后一学期才开始，开题、审查、格式和毕业材料都要提前排。',
    body: `先确认院系论文流程：选导师、研究计划、开题、伦理审查、数据收集、中期反馈、正式审查和最终提交。每一步都有截止时间，导师回复慢、格式修改和补材料都会拖延。若可能延期，提前问学校国际处延毕、注册和签证衔接，不要等系统关闭后再补救。`,
    createdAt: '2026-04-26',
    updatedAt: '2026-04-26',
    featured: true
  },
  {
    id: 'post-secondhand-trade',
    slug: 'post-secondhand-trade',
    title: '韩国二手交易避坑：电器、家具和面交检查清单',
    summary: '买二手电器家具时，重点看实拍、功能测试、搬运费用和付款方式。',
    school: '韩国生活',
    category: '跳蚤市场',
    author: '搬家买家具的人',
    price: 0,
    hot: '二手',
    views: 2260,
    likes: 98,
    bookmarks: 220,
    tags: ['二手交易', '家具', '电器', '面交'],
    excerpt: '二手交易不要只看便宜，先确认能不能现场测试、谁负责搬运和售后怎么说。',
    body: `买冰箱、微波炉、洗衣机和桌椅时，要求实拍和视频测试，确认尺寸、楼层、电梯和搬运方式。面交优先，付款尽量留痕。不要先转大额定金给陌生人。电器要检查插头、噪音、制冷或加热、漏水和外观损坏。卖旧家具时也要提前确认大型废弃物处理规则。`,
    createdAt: '2026-04-25',
    updatedAt: '2026-04-25',
    featured: false
  },
  {
    id: 'post-trash-sorting',
    slug: 'post-trash-sorting',
    title: '韩国垃圾分类：一般垃圾、厨余和大件怎么扔',
    summary: '不同地区规则会不同，但一般要区分普通垃圾、厨余、回收和大型废弃物。',
    school: '韩国生活',
    category: '周边生活攻略',
    author: '刚搬进 one-room',
    price: 0,
    hot: '生活',
    views: 2040,
    likes: 86,
    bookmarks: 190,
    tags: ['垃圾分类', '厨余', '大型废弃物', '生活'],
    excerpt: '垃圾分类不清楚先问房东或区厅，别把大件家具直接丢在楼下。',
    body: `韩国常见垃圾包括一般垃圾、厨余垃圾、可回收物和大型废弃物。一般垃圾通常需要指定垃圾袋，厨余要看住宅规则，可回收物要清洗后分类。家具、床垫、电器等大件一般需要申请或购买贴纸。不同区规则不同，搬家前先问房东、管理室或区厅。`,
    createdAt: '2026-04-24',
    updatedAt: '2026-04-24',
    featured: false
  },
  {
    id: 'post-traffic-card',
    slug: 'post-traffic-card',
    title: '韩国交通卡和通学路线：先算时间再看房',
    summary: '找房和选校区时，地铁、公交、坡度、末班车和换乘次数都要一起看。',
    school: '韩国生活',
    category: '周边生活攻略',
    author: '通学党',
    price: 0,
    hot: '交通',
    views: 1980,
    likes: 75,
    bookmarks: 160,
    tags: ['交通卡', '通学', '地铁', '公交'],
    excerpt: '地图显示 20 分钟不等于每天轻松通学，坡路和末班车也很关键。',
    body: `韩国通学不只看直线距离。选房时打开地图模拟早高峰路线，确认地铁和公交换乘、步行坡度、雨雪天路线、末班车和夜路安全。交通卡可以绑定部分银行卡或手机服务，具体功能看银行、运营商和交通卡产品说明。`,
    createdAt: '2026-04-23',
    updatedAt: '2026-04-23',
    featured: false
  },
  {
    id: 'post-scholarship',
    slug: 'post-scholarship',
    title: '韩国大学奖学金：别只看入学奖，还要看维持条件',
    summary: '奖学金要看语言成绩、GPA、减免比例、续奖条件和是否自动审核。',
    school: '韩国大学',
    category: '入学须知',
    author: '拿过奖学金的同学',
    price: 0,
    hot: '奖学金',
    views: 2470,
    likes: 132,
    bookmarks: 300,
    tags: ['奖学金', 'GPA', 'TOPIK', '入学'],
    excerpt: '入学奖学金拿到不代表每学期都有，续奖条件要提前看。',
    body: `申请前看清奖学金类型：入学奖、成绩奖、语言成绩奖、院系奖、外部奖。重点不是第一学期减免多少，而是续奖是否看 GPA、学分、出勤、TOPIK 或院系推荐。不同学校政策变化很快，最终以学校招生简章和奖学金公告为准。`,
    createdAt: '2026-04-22',
    updatedAt: '2026-04-22',
    featured: false
  },
  {
    id: 'post-korea-useful-sites',
    slug: 'post-korea-useful-sites',
    title: '韩国留学生常用网站：签证、学校、生活和求职入口',
    summary: '把 HiKorea、Study in Korea、学校国际处、保险和求职相关入口按场景整理。',
    school: '韩国生活',
    category: '周边生活攻略',
    author: '资料整理员',
    price: 0,
    hot: '工具',
    views: 2860,
    likes: 150,
    bookmarks: 380,
    tags: ['HiKorea', 'Study in Korea', '网站', '工具'],
    excerpt: '遇到签证、登录证、入学和生活问题，先看官方入口再问经验。',
    body: `常用入口包括 HiKorea、Korea Visa Portal、Study in Korea、学校国际处、国民健康保险英文页面、区厅生活信息、求职平台和学校就业中心。经验帖可以帮你理解流程，但最终材料、期限和政策结论要回到官方公告确认。建议把常用链接收藏到浏览器和手机备忘录。`,
    createdAt: '2026-04-21',
    updatedAt: '2026-04-21',
    featured: true
  },
  {
    id: 'post-language-to-undergrad',
    slug: 'post-language-to-undergrad',
    title: '语学院转本科：材料、出勤和语言成绩怎么衔接',
    summary: '语学院经历可以帮助适应，但本科申请仍要按招生简章准备材料。',
    school: '庆熙大学',
    category: '入学须知',
    author: '语学院转本科学姐',
    price: 0,
    hot: '入学',
    views: 2580,
    likes: 121,
    bookmarks: 270,
    tags: ['语学院', '本科申请', 'TOPIK', '出勤'],
    excerpt: '语学院转本科不要只看级数，出勤、成绩、学历材料和申请时间线都重要。',
    body: `语学院转本科先确认目标学校是否认可本校语学院等级，是否仍要求 TOPIK 或其他语言证明。准备材料包括学历材料、成绩、语言证明、护照、申请表、财力材料和专业补充材料。出勤和成绩不好可能影响推荐或内部判断。以当季外国人招生简章为准。`,
    createdAt: '2026-04-20',
    updatedAt: '2026-04-20',
    featured: false
  },
  {
    id: 'post-wage-dispute',
    slug: 'post-wage-dispute',
    title: '兼职工资纠纷：聊天记录、排班和转账怎么留证',
    summary: '工资被拖欠时先整理证据，再决定找学校、咨询窗口或劳动渠道。',
    school: '韩国生活',
    category: '找兼职与代兼职',
    author: '兼职被拖款',
    price: 0,
    hot: '避坑',
    views: 2340,
    likes: 108,
    bookmarks: 240,
    tags: ['工资拖欠', '兼职', '劳动纠纷', '证据'],
    excerpt: '工资纠纷时不要只在群里吐槽，先把能证明劳动关系和金额的证据保存好。',
    body: `保留劳动合同、排班表、打卡记录、聊天记录、转账记录、店铺名称、营业地址和雇主联系方式。沟通时尽量用文字确认工作时间、工资标准和结算日。若要进一步处理，可先问学校国际处、1345 或劳动咨询渠道。打工许可和劳动处理以官方窗口说明为准。`,
    createdAt: '2026-04-19',
    updatedAt: '2026-04-19',
    featured: false
  },
  {
    id: 'post-graduation-documents',
    slug: 'post-graduation-documents',
    title: '毕业材料准备：成绩单、学位证明和回国认证前先看清',
    summary: '毕业材料不要等回国前一天才开，先区分学校证明、翻译、公证和认证需求。',
    school: '韩国大学',
    category: '作业与论文',
    author: '准毕业生',
    price: 0,
    hot: '毕业',
    views: 2120,
    likes: 95,
    bookmarks: 210,
    tags: ['毕业材料', '成绩单', '学位证明', '认证'],
    excerpt: '不同用途需要的材料不同，学校能开的证明、语言版本和时间点要提前确认。',
    body: `毕业前先列用途：求职、升学、签证、回国认证或公司入职。再确认成绩单、毕业证明、学位证明、在学期间证明、英文或韩文版本、是否需要密封件、是否能线上开具。部分材料要毕业处理完成后才能开，不要把所有时间压在离境前。`,
    createdAt: '2026-04-18',
    updatedAt: '2026-04-18',
    featured: false
  }
]

const feedImages = [
  'https://shouye.fun/schools/yonsei/1.jpg',
  'https://shouye.fun/schools/cau/1.jpg',
  'https://shouye.fun/schools/hongik/1.jpg',
  'https://shouye.fun/schools/sogang/1.jpg',
  'https://shouye.fun/schools/konkuk/1.jpg',
  'https://shouye.fun/schools/uos/1.jpg',
  'https://shouye.fun/home-hero/2.jpg',
  'https://shouye.fun/home-hero/3.jpg'
]

const merchantCards = [
  {
    id: 'm_wala_1',
    type: '留学咨询',
    title: '瓦剌留学｜申请材料与签证规划',
    subtitle: '先看材料范围、院校风险和签证节点，再决定要不要咨询。',
    image: '/assets/merchant/merchant-wala.jpg',
    author: '瓦剌留学',
    likes: 268,
    tags: ['择校', '材料审查', '续签']
  },
  {
    id: 'm_food_1',
    type: '餐饮相关',
    title: '校园餐饮团购｜按学校看优惠',
    subtitle: '中餐、外卖、夜宵和团购券，适合新生先按地区筛。',
    image: '/assets/merchant/merchant-food.jpg',
    author: '校园商家',
    likes: 134,
    tags: ['中餐', '外卖', '团购']
  },
  {
    id: 'm_home_1',
    type: '家政搬家',
    title: '退租清洁和搬家怎么比价？',
    subtitle: '看服务范围、可预约时间、费用计算方式和真实评价。',
    image: '/assets/merchant/merchant-home.jpg',
    author: '生活服务',
    likes: 97,
    tags: ['搬家', '清洁', '维修']
  }
]

module.exports = {
  schools,
  questionCategories,
  postCategories,
  skillCategories,
  partnerCategories,
  fallbackQuestions,
  fallbackPosts,
  feedImages,
  merchantCards
}
