const merchantCategories = [
  { id: 'consulting', title: '留学咨询', subtitle: '择校、材料、签证、语学院和大学院申请' },
  { id: 'thesis', title: '论文与毕业', subtitle: '论文流程、发表准备、延毕材料和毕业审查' },
  { id: 'korean', title: '韩语培训', subtitle: 'TOPIK、韩语写作、口语面试和语学院衔接' },
  { id: 'art', title: '艺术类培训', subtitle: '作品集、面试准备、设计/传媒/音乐/表演方向' },
  { id: 'portfolio', title: '作品集辅导', subtitle: '艺术、设计、传媒、建筑和影像方向规划与修改' },
  { id: 'food', title: '餐饮相关', subtitle: '中餐、外卖、夜宵、聚餐和校园团购' },
  { id: 'logistics', title: '物流快递', subtitle: '行李托运、海运、转运、同城配送和文件快递' },
  { id: 'telecom', title: '通信', subtitle: '电话卡、流量卡、宽带、Wi-Fi 和号码实名' },
  { id: 'home', title: '家政搬家', subtitle: '搬家、退租清洁、家具处理、维修和上门安装' },
  { id: 'housing', title: '不动产', subtitle: '找房、转租、保证金风险和合同确认' },
]

const merchantCards = [
  {
    id: 'wala-study',
    type: '留学咨询',
    title: '韩国留学申请、签证续签、语学院和大学院规划',
    subtitle: '瓦剌留学专注韩国院校申请与在韩升学规划，适合准备申请或已经在韩转阶段的学生对比咨询。',
    image: '/assets/merchant/merchant-wala.jpg',
    author: '瓦剌留学',
    logo: '瓦',
    logoImage: '/assets/merchant/merchant-wala.jpg',
    likes: 268,
    level: 'normal',
    tags: ['择校', '材料审核', '签证续签'],
    detailSections: [
      { title: '适合咨询的人', text: '准备韩国语学院、本科、大学院申请，或需要续签材料和院校规划的学生。' },
      { title: '咨询前先准备', text: '学校、专业方向、毕业时间、语言成绩、预算和目前卡住的具体节点。' },
      { title: '平台提醒', text: '展示服务边界和咨询方向，不代替学校、出入境和官方窗口的最新公告。' },
    ],
  },
  {
    id: 'tuzhuren-thesis',
    type: '论文与毕业',
    title: '韩国论文流程、毕业审查、韩文发表和延毕节点支持',
    subtitle: '土著人面向本科、大学院和毕业阶段学生，展示论文流程说明、毕业材料检查、韩文表达校对和发表准备等合规学业支持服务。',
    image: '/assets/merchant/merchant-academic.jpg',
    author: '土著人',
    logo: '土',
    logoImage: '/assets/merchant/merchant-academic.jpg',
    likes: 318,
    level: 'pinned',
    bubbleColor: 'rgba(194, 151, 62, 0.92)',
    tags: ['论文流程', '毕业审查', '韩文发表'],
    detailSections: [
      { title: '适合咨询的人', text: '正在准备论文、毕业材料、发表稿、延毕申请或学院窗口材料的本科、大学院和毕业阶段学生。' },
      { title: '咨询前先准备', text: '学校、专业、毕业要求、论文阶段、导师反馈、提交节点和目前遇到的具体卡点。' },
      { title: '平台提醒', text: '只展示合规学业支持边界，不提供代写、代投、替考、伪造材料等服务。' },
    ],
  },
  {
    id: 'saguatu-portfolio',
    type: '作品集辅导',
    title: '艺术作品集、面试准备和设计传媒方向申请',
    subtitle: '傻呱兔作品集面向艺术、设计、传媒、建筑、影像等方向，展示作品集规划、排版修改和面试准备服务。',
    image: '/assets/merchant/merchant-academic.jpg',
    author: '傻呱兔作品集',
    logo: '兔',
    likes: 226,
    level: 'pinned',
    tags: ['作品集', '面试准备', '艺术申请'],
    detailSections: [
      { title: '适合咨询的人', text: '准备艺术类本科、大学院、插班或作品集补强的学生。' },
      { title: '咨询前先准备', text: '目标学校、专业方向、已有作品、申请时间线、语言状态和希望修改的部分。' },
      { title: '平台提醒', text: '服务应围绕规划、表达、排版和修改建议，不承诺录取结果。' },
    ],
  },
  {
    id: 'korean-topik',
    type: '韩语培训',
    title: 'TOPIK 写作训练和韩语口语面试准备',
    subtitle: '按目标等级、考试时间、写作短板和面试场景拆分训练任务，适合申请和升学衔接。',
    image: '/assets/merchant/merchant-academic.jpg',
    author: '韩语训练室',
    logo: '韩',
    likes: 188,
    level: 'normal',
    tags: ['TOPIK', '韩语写作', '口语面试'],
  },
  {
    id: 'art-interview',
    type: '艺术类培训',
    title: '音乐/表演/影像方向面试和材料准备',
    subtitle: '展示面试准备、材料表达、作品说明和专业方向梳理，适合艺术类申请前对比。',
    image: '/assets/merchant/merchant-academic.jpg',
    author: '艺考面试课',
    logo: '艺',
    likes: 145,
    level: 'normal',
    tags: ['面试', '作品说明', '表演影像'],
  },
  {
    id: 'food-campus',
    type: '餐饮相关',
    title: '校园餐饮与团购优惠',
    subtitle: '中餐、外卖、夜宵、聚餐和校区团购，按学校和地区触达附近学生。',
    image: '/assets/merchant/merchant-food.jpg',
    author: '校园餐饮',
    logo: '餐',
    likes: 134,
    level: 'normal',
    tags: ['中餐', '外卖', '团购'],
  },
  {
    id: 'logistics-docs',
    type: '物流快递',
    title: '文件快递、行李托运和同城配送',
    subtitle: '看时效、可寄物品、赔付规则和上门范围，适合搬家和材料递送前比价。',
    image: '/assets/merchant/merchant-logistics.jpg',
    author: '物流快递',
    logo: '物',
    likes: 92,
    level: 'normal',
    tags: ['海运', '文件', '同城配送'],
  },
  {
    id: 'telecom-plan',
    type: '通信',
    title: '新生电话卡和网络套餐',
    subtitle: '先确认实名材料、合约期限、解约金和校园附近网点。',
    image: '/assets/merchant/merchant-telecom.jpg',
    author: '通信商家',
    logo: '通',
    likes: 156,
    level: 'normal',
    tags: ['手机卡', '宽带', '实名'],
  },
  {
    id: 'home-moving',
    type: '家政搬家',
    title: '搬家清洁与家政维修',
    subtitle: '展示服务范围、预约时间、费用计算方式和真实评价，适合围绕开学季与退租季投放。',
    image: '/assets/merchant/merchant-home.jpg',
    author: '生活服务',
    logo: '清',
    likes: 97,
    level: 'normal',
    tags: ['搬家', '清洁', '维修'],
  },
  {
    id: 'housing-room',
    type: '不动产',
    title: '学校周边找房和转租合同核对',
    subtitle: '看区域、保证金、合同确认方式和中介资质，减少学生反复问价成本。',
    image: '/assets/merchant/merchant-housing.jpg',
    author: '房源服务',
    logo: '房',
    likes: 201,
    level: 'normal',
    tags: ['找房', '转租', '合同'],
  },
]

function getMerchantById(id) {
  return merchantCards.find((item) => item.id === id)
}

function withBrandAccess(cards, accesses = []) {
  return cards.map((card) => {
    const access = accesses.find((item) => item.brandId === card.id || item.brandName === card.author)
    return access ? { ...card, level: access.level || card.level } : card
  })
}

module.exports = {
  merchantCategories,
  merchantCards,
  getMerchantById,
  withBrandAccess,
}
